In [1]:
import torch

tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [2]:
tensor + 10

tensor([11, 12, 13])

In [3]:
tensor - 2

tensor([-1,  0,  1])

In [4]:
tensor * 2

tensor([2, 4, 6])

In [5]:
torch.mul(tensor, 3)

tensor([3, 6, 9])

In [7]:
torch.add(tensor, 3)

tensor([4, 5, 6])

In [10]:
# element wise multiplication

print(tensor, "*", tensor, "=", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [12]:
# matrix multiplication (dot product)

torch.matmul(tensor, tensor)

tensor(14)

In [15]:
# 1*7 + 2*9 + 3*11
torch.matmul(torch.tensor([1, 2, 3]), torch.tensor([7, 9, 11]))

tensor(58)

In [19]:
%%time
value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value

CPU times: total: 0 ns
Wall time: 186 μs


tensor(14)

In [20]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 53.9 μs


tensor(14)

matrix multiplication:

- inner dimension must match
    - `(2,3) @ (2,3)` won't work
    - `(2,3) @ (3,2)` will work

- the resulting matrix has the outer dimension
    - `(2,3) @ (3,2)` -> `(2,2)`

In [21]:
tensor @ tensor

tensor(14)

In [23]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.3090, 0.8117],
        [0.5286, 0.8631]])

In [24]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.9177, 0.9640, 0.9665],
        [0.2785, 0.3627, 0.4090],
        [0.1811, 0.2724, 0.3263]])

In [25]:
torch.mm(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.3558, 0.1109, 0.1533],
        [0.5886, 0.3742, 0.2070],
        [1.1075, 0.5622, 0.4241]])

torch mm = matmul (alias)