# Reshapeing, stacking, squeezing and unsqueezing tensors

- Reshape - reshape an input to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on each other (vstack) or side by side (hstack)
- Squeeze - removes all '1' dimensions from a tensor
- Unsqueeze - add a '1' dimension to a target tensor
- Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [1]:
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
# add an extra dimension

# x_reshaped = x.reshape(1, 7)
# RuntimeError: shape '[1, 7]' is invalid for input of size 9

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [3]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [4]:
x = torch.arange(1., 11.)
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [5]:
x = torch.arange(1., 10.)
z = x.view(1, 9)
z, z.shape
# z is just a different view of x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [6]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [7]:
# stack
torch.stack([x, x, x])

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [8]:
torch.stack([x, x, x], dim=1)

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [9]:
# squeeze, unsqueeze
torch.squeeze(x)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [11]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [12]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [13]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [14]:
y = torch.squeeze(x, (1, 2, 3))
y.size()

torch.Size([2, 2, 2])

In [15]:
x.shape

torch.Size([2, 1, 2, 1, 2])

In [16]:
y = torch.squeeze(x)
y.shape

torch.Size([2, 2, 2])

In [17]:
y.unsqueeze(0).shape

torch.Size([1, 2, 2, 2])

In [18]:
y.unsqueeze(1).shape

torch.Size([2, 1, 2, 2])

In [19]:
# permute
x = torch.rand(2, 3, 5)
x.shape

torch.Size([2, 3, 5])

In [20]:
torch.permute(x, (2, 0, 1)).shape

torch.Size([5, 2, 3])

In [21]:
x_original = torch.rand(size=(224, 224, 3))  # height, width, color_channel
x_original.shape

torch.Size([224, 224, 3])

In [22]:
# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
# color_channel, height, width

In [23]:
x = torch.zeros(5, 5, 3)
x[:, :, 2] = 1
# it is probably wrong!
x

tensor([[[0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.]],

        [[0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.]],

        [[0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.]],

        [[0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.]],

        [[0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.],
         [0., 0., 1.]]])

In [24]:
x_permuted = x.permute(2, 0, 1)
x_permuted

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [25]:
x_permuted.shape

torch.Size([3, 5, 5])

In [26]:
x_permuted[0]

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [27]:
# https://youtu.be/Z_ikDlimN6A?si=0jn2wb5Uhip_zhgl&t=12184