# Indexing

Selecting data from tensor by index. (Similar to numpy)

In [3]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
# middle bracket (dim=1)
# x[0,0] = x[0][0]

x[0][0]

tensor([1, 2, 3])

In [16]:
# 3rd dimension

x[0][1][2]

tensor(6)

In [21]:
x[0][1]

tensor([4, 5, 6])

In [22]:
# use : to select all of a target dimension

x[:, 0]

tensor([[1, 2, 3]])

In [23]:
# get all values of 0th and 1st dimension, but only index 1 of 2nd dimension

x[:, :, 1]

tensor([[2, 5, 8]])

In [28]:
x[0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
x[0, 0, :]

tensor([1, 2, 3])

In [30]:
x[0, :, 2]

tensor([3, 6, 9])