Numpy is a popular scientific computing library.

- Data in numpy array, want in PyTorch tensor. -> `torch.from_numpy(ndarray)`
- tensor -> numpy = `torch.Tensor.numpy()`

In [1]:
# numpy to torch
import numpy as np
import torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
array.dtype

dtype('float64')

In [3]:
tensor = torch.from_numpy(array).type(torch.float32)

tensor.dtype

torch.float32

In [4]:
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [5]:
# change value in array
array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [6]:
# tensor -> numpy

tensor = torch.ones(7)
nparray = tensor.numpy()

tensor, nparray

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [7]:
tensor = tensor + 1

tensor, nparray

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))