# Reproducibility

Trying to take out random of random.

In short how a NN learns:

- start with random numbers
- tensor operations
- update random numbers


In [3]:
import torch

In [7]:
torch.rand(3, 3)

tensor([[0.2665, 0.1184, 0.7491],
        [0.5827, 0.5568, 0.9863],
        [0.7899, 0.8184, 0.2684]])

In [8]:
torch.rand(3, 3) == torch.rand(3, 3)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [11]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
t1 = torch.randn(3, 3)

torch.manual_seed(RANDOM_SEED)
t2 = torch.randn(3, 3)

t1, t2, t1 == t2

(tensor([[ 0.3367,  0.1288,  0.2345],
         [ 0.2303, -1.1229, -0.1863],
         [ 2.2082, -0.6380,  0.4617]]),
 tensor([[ 0.3367,  0.1288,  0.2345],
         [ 0.2303, -1.1229, -0.1863],
         [ 2.2082, -0.6380,  0.4617]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [12]:
# random number generators in other libraries

import random
random.seed(0)

import numpy as np
np.random.seed(0)