# Running tensors and PyTorch objects on GPUs

and making faster computations...

GPU driver = CUDA

In [1]:
# getting a GPU
import torch

torch.cuda.is_available()

True

In [2]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
# count numbers of GPUs
torch.cuda.device_count()

1

In [4]:
# tensor on CPU, not on GPU
tensor = torch.tensor([1, 2, 3], device='cpu')
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [5]:
# move tensor to GPU if available

tensor_on_gpu = tensor.to(device=device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [6]:
# numpy works only on CPU, move tensor back to cpu

# tensor_on_gpu.numpy()
# TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

tensor_on_gpu.cpu().numpy()

array([1, 2, 3])